name: flutter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  auto_route: ^0.6.9
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_sign_in: ^4.5.6
  injectable: ^1.0.5
  uuid: ^2.2.2
  kt_dart: ^0.8.0

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.4
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  lint: ^1.3.0

flutter:
  uses-material-design: true
