name: flutter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.20
  auto_route: ^2.2.0
  cloud_firestore: ^2.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.1
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.1
  get_it: ^7.1.3
  google_sign_in: ^5.0.2
  injectable: ^1.4.0
  json_annotation: ^4.0.1
  kt_dart: ^0.9.0
  rxdart: ^0.27.0
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter:
  uses-material-design: true
