name: fluter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.4
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  get_it: ^4.0.4
  injectable: ^1.0.4
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  freezed: ^0.11.6
  lint: ^1.2.0
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true
