name: fluter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.4
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  freezed: ^0.11.6

flutter:
  uses-material-design: true
