name: flutter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  auto_route: ^0.6.9
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  firebase_auth: 0.20.0+1
  firebase_core: ^0.7.0
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.4
  google_sign_in: ^4.5.9
  injectable: ^1.0.7
  json_annotation: ^3.0.1
  kt_dart: ^0.8.0
  uuid: ^2.2.2

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.13
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  json_serializable: ^3.3.0
  lint: ^1.5.1

flutter:
  uses-material-design: true
